CC = c++
CFLAGS = -Wall

all: aufgabe20 aufgabe21
	

aufgabe20: aufgabe20.cpp
	$(CC) $(CLFAGS) -o aufgabe20 aufgabe20.cpp

aufgabe21: aufgabe21.cpp mlcgXOR.cpp mlcgXOR.hpp
	$(CC) $(CFLAGS) -o aufgabe21 aufgabe21.cpp mlcgXOR.cpp

clean: 
	rm aufgabe20 aufgabe21