CC = c++
CFLAGS = -Wall

all : aufgabe22 aufgabe23


aufgabe22: aufgabe22.cpp 
	$(CC) $(CFLAGS) -o aufgabe22 aufgabe22.cpp
	
aufgabe23: aufgabe23.cpp derive.hpp
	$(CC) $(CFLAGS) -o aufgabe23 aufgabe23.cpp

clean:
	rm -f aufgabe23 aufgabe22
	


