CC = c++
CFLAGS = -Wall

all: aufgabe10.cpp swap.cpp swap.hpp
	$(CC) $(CFLAGS) -o aufgabe10 aufgabe10.cpp swap.cpp
	$(CC) $(CFLAGS) -o aufgabe11 aufgabe11.cpp



aufgabe10: aufgabe10.cpp swap.cpp swap.hpp
	$(CC) $(CFLAGS) -o aufgabe10 aufgabe10.cpp swap.cpp

aufgabe11: aufgabe11.cpp 
	$(CC) $(CFLAGS) -o aufgabe11 aufgabe11.cpp 


clean: 	
	rm aufgabe11 aufgabe10