
CC = c++
CFLAGS = -Wall

all: aufgabe15 aufgabe16



aufgabe15: aufgabe15.cpp Vektor.cpp Vektor.hpp
	$(CC) $(CFLAGS) -o aufgabe15 aufgabe15.cpp Vektor.cpp

aufgabe16: aufgabe16.cpp
	$(CC) $(CFLAGS) -o aufgabe16 aufgabe16.cpp

clean: 
	rm aufgabe16 aufgabe15
	
